### ISSUE TITLE
Quickloot offene Truhen mit Rüstung

### ISSUE THREAD

**Issue by Cutesty** [Kirides/ninja-quickloot#1]
wenn man offene Truhen, die Rüstungen beinhalten, quicklootet, wird die Rüstung nicht gelootet und sie verschwindet aus der Truhe.
Beispiel: Start des Spiels auf Loberts Hof mit der Bauernkleidung oder das Warenlager mit verschiedenen Rüstungen in Khorinis

**Comment by kirides** [comment]
Richtig, dieser Patch hat einige Probleme und sollte nicht verwendet werden. Er ist nur ein Prototyp.

Für ein funktionierendes Quickloot kann ich entweder das G2_NR (Quickloot, Quicksafe ... Von Liker) empfehlen, oder mein Union Plugin (Quickloot+Manareg, einzeln abschaltbar) https://github.com/Kirides/union-plugin

Die dll ist unter den Releases und erfordert Union 1.0h.

**Comment by kirides** [comment]
> wenn man offene Truhen, die Rüstungen beinhalten, quicklootet, wird die Rüstung nicht gelootet und sie verschwindet aus der Truhe.
> Beispiel: Start des Spiels auf Loberts Hof mit der Bauernkleidung oder das Warenlager mit verschiedenen Rüstungen in Khorinis

Wenn du einen Patch brauchst, welcher besser funktioniert, dann nimm das aktuelle Release:
https://github.com/Kirides/ninja-quickloot/releases

Hier werden Truhen korrekt gelootet.

**Comment by kirides** [comment]
Behoben mit [#ddf626a](https://github.com/Kirides/ninja-quickloot/commit/ddf626a2ca3d79aed83d8cfc259ea1af689ebcc9)
