### ISSUE TITLE
Diebstahl wird nicht bemerkt.

### ISSUE THREAD

**Issue by goteksc** [Kirides/ninja-quickloot#2]
> Diebstähle werden mit diesem Patch ebenfalls bemerkt.
Glaubt nicht ihr könnt einfach in Häuser eindringen und ungestraft alles klauen ;)

Das kann ich nicht bestätigen. Ist mir leider erst viel zu spät nachdem ich die ganze Stadt Ahssûn ausgeräumt hatte aufgefallen mit:
```
Player Kit 2.8 + Patch for x64 Systems (Ressourcenmanager)
Union 1.0k (Ressourcenmanager)
Ninja-2.6.10
Legend of Ahssûn 1.1
Autosave.vdf
BetterTorches.vdf
ChangeGangart.vdf
PickLockHelper.vdf
Quickloot.vdf
```
Auch nicht in G2 DNdR 2.6f mit SystemPack 1.8 *oder* Union1.0k und außer Quickloot sonst keine anderen ninja/union patches wurden Diebstähle nicht bemerkt. Komplett frisches Savegame, direkt nach Xardas ins Obere Viertel geflogen.

Testweise:
Im Oberen Viertel in ein Haus rennen, warten bis Wachen/Bürger reinkommen, und dann jeweils mit LMB oder RMB einmal klauen.
Quickloot per RMB gab keine Reaktion, normal looten mit LMB aber doch.

**Comment by kirides** [comment]
gefixt mit release [v1.9.5](https://github.com/Kirides/ninja-quickloot/releases/tag/v1.9.5)
