### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by kubinka0505** [Kirides/ninja-quickloot#4]
Hello, the plugin turns on with the game, but when pressing the right mouse button nothing happens.
Settings from `ReadMe.md` were pasted into `Gothic.ini`, however, this does not help.

I tested the plugin on NOTR with Union `1.0k`.

How can it be fixed?

**Comment by kirides** [comment]
This "plugin" is a patch based on Ninja, so you'd first have to make sure Ninja is working properly.
